language: generic
sudo: required
services:
  -docker

before_install:
  -docker build -t filip123go/docker-react -f Dockerfile.dev .

script:
  -docker run -e CI=true filip123go/docker-react npm run test